controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use kartik\mpdf\Pdf;
use app\models\Users;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    

    public function actionPrintlist()
    {   
        Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        $headers = Yii::$app->response->headers;
        $headers->add('Content-Type', 'application/pdf');

        $content = $this->renderPartial('print',[
            
        ]);

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
                // A4 paper format
            'format' => Pdf::FORMAT_A4, 
                // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
                // stream to browser inline
            'destination' => Pdf::DEST_BROWSER, 
                // your html content input
            'content' => $content,  
                // format content from your own css file if needed or use the
                // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
                // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
                // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
                // call mPDF methods on the fly
            'methods' => [ 
                'SetHeader'=>['ПЕЧАТЬ РАСЧЕТА'], 
                'SetFooter' => ['|{PAGENO}/{nbpg}'],
            ]
        ]);
       
        return $pdf->render();
    }

    



    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
    	if (Yii::$app->user->isGuest) {
            return $this->redirect(['/site/login']);
        }
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['login']);
    }

    public function actionAvtorizatsiya()
    {
      if(isset(Yii::$app->user->identity->id))
      {
        return $this->render('error');
      }        
       else
        {
            Yii::$app->user->logout();
            $this->redirect(['login']);
        }

    }

    public function actionSetThemeValues()
    {
        $session = Yii::$app->session;
        if (isset($_POST['sd_position'])) $session['sd_position'] = $_POST['sd_position'];

        if (isset($_POST['header_styling'])) $session['header_styling'] = $_POST['header_styling'];

        if (isset($_POST['sd_styling'])) $session['sd_styling'] = $_POST['sd_styling'];

        if (isset($_POST['cn_gradiyent'])) $session['cn_gradiyent'] = $_POST['cn_gradiyent'];

        if (isset($_POST['cn_style'])) $session['cn_style'] = $_POST['cn_style'];

        if (isset($_POST['boxed'])) $session['boxed'] = $_POST['boxed'];

    }

    public function actionSdPosition()
    {
        $session = Yii::$app->session;
        if($session['sd_position'] != null) return $session['sd_position'];
        else return 1;
    }

    public function actionHeaderStyling()
    {
        $session = Yii::$app->session;
        if($session['header_styling'] != null) return $session['header_styling'];
        else return 1;
    } 

    public function actionSdStyling()
    {
        $session = Yii::$app->session;
        if($session['sd_styling'] != null) return $session['sd_styling'];
        else return 1;
    } 

    public function actionCnGradiyent()
    {
        $session = Yii::$app->session;
        if($session['cn_gradiyent'] != null) return $session['cn_gradiyent'];
        else return 1;
    } 

    public function actionCnStyle()
    {
        $session = Yii::$app->session;
        if($session['cn_style'] != null) return $session['cn_style'];
        else return 1;
    } 
    public function actionBoxed()
    {
        $session = Yii::$app->session;
        if($session['boxed'] != null) return $session['boxed'];
        else return 1;
    } 

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <!-- begin error -->
    <div class="error">
        <div class="error-code m-b-10"><?=$exception->statusCode?> <i class="fa fa-warning"></i></div>
        <div class="error-content">
            <div class="error-message"><?=$message?></div>
            <div class="error-desc m-b-20">
                Если это ошибка сервера. <br>
                Свяжитесь с тех поддержкой.
            </div>
            <div>
                <a href="/" class="btn btn-success">На главную</a>
            </div>
        </div>
    </div>
    <!-- end error -->

</div>

views/site/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;


/* @var $this yii\web\View */

$this->title = 'Color Admin ';
?>
    <!-- begin row -->
    <div class="row">
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-green">
                <div class="stats-icon"><i class="fa fa-desktop"></i></div>
                <div class="stats-info">
                    <h4>TOTAL VISITORS</h4>
                    <p>3,291,922</p>    
                </div>
                <div class="stats-link">
                    <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-blue">
                <div class="stats-icon"><i class="fa fa-chain-broken"></i></div>
                <div class="stats-info">
                    <h4>BOUNCE RATE</h4>
                    <p>20.44%</p>   
                </div>
                <div class="stats-link">
                    <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-purple">
                <div class="stats-icon"><i class="fa fa-users"></i></div>
                <div class="stats-info">
                    <h4>UNIQUE VISITORS</h4>
                    <p>1,291,922</p>    
                </div>
                <div class="stats-link">
                    <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
        <!-- begin col-3 -->
        <div class="col-md-3 col-sm-6">
            <div class="widget widget-stats bg-red">
                <div class="stats-icon"><i class="fa fa-clock-o"></i></div>
                <div class="stats-info">
                    <h4>AVG TIME ON SITE</h4>
                    <p>00:12:23</p> 
                </div>
                <div class="stats-link">
                    <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
                </div>
            </div>
        </div>
        <!-- end col-3 -->
    </div>
    <!-- end row -->
    <!-- begin row -->
    <div class="row">
        <!-- begin col-8 -->
        <button type="button" class="btn btn-info btn-rounded pull-right"> <a class="fa fa-print" data-pjax=0 target="_blank" href=" <?=Url::toRoute(['site/printlist'])?>">Печатать</a></button>
    </div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Авторизация';

$fieldOptions1 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group m-b-20'],
    'inputTemplate' => "{input}"
];
?>
<div class="login login-v2">
    <!-- begin brand -->
    <div class="login-header">
        <div class="brand">
            <span class="logo"></span> <?=Yii::$app->name?>
            <small>Введите данные для авторизации</small>
        </div>
        <div class="icon">
            <i class="fa fa-sign-in"></i>
        </div>
    </div>
    <!-- end brand -->
    <div class="login-content">
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('email'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('password'), 'class' => 'form-control input-lg inverse-mode no-border']) ?>
        <div class="login-buttons">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-success btn-block btn-lg', 'name' => 'login-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/print.php
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="9" style=" text-align: left; font-size: 20px; padding-left: 10px;">ЛДСП</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">№ детали</th>
            <th  style=" text-align: center;padding:3px;">Цвет</th>
            <th  style=" text-align: center;padding:3px;">Толщина</th>
            <th  style=" text-align: center;padding:3px;">Длина</th>
            <th  style=" text-align: center;padding:3px;">Ширина</th>
            <th  style=" text-align: center;padding:3px;">Количество</th>
            <th  style=" text-align: center;padding:3px;">Кромка по длине</th>
            <th  style=" text-align: center;padding:3px;">Кромка по ширине</th>
            <th  style=" text-align: center;padding:3px;">Примечание</th>


        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">Материал заказчика</td>
            <td style=" text-align: left;padding:3px;">16</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">Нет - Нет</td>
            <td style=" text-align: left;padding:3px;">Нет - Нет</td>
            <td style=" text-align: left;padding:3px;">-</td>
        </tr>
    </tbody>
</table>
<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="6" style=" text-align: left; font-size: 20px; padding-left: 10px;">Оргалит</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">№ детали</th>
            <th  style=" text-align: center;padding:3px;">Цвет</th>
            <th  style=" text-align: center;padding:3px;">Длина</th>
            <th  style=" text-align: center;padding:3px;">Ширина</th>
            <th  style=" text-align: center;padding:3px;">Количество</th>
            <th  style=" text-align: center;padding:3px;">Примечание</th>


        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">Материал заказчика</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">300</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">-</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="3" style=" text-align: left; font-size: 20px; padding-left: 10px;">Эскизы (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">Радиус 50-400 мм</th>
            <th  style=" text-align: center;padding:3px;">Радиус 450-1000 мм</th>
            <th  style=" text-align: center;padding:3px;">Прямоугольный выпил</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">3</td>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">1</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="4" style=" text-align: left; font-size: 20px; padding-left: 10px;">Фрезеровка (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center;padding:3px;">Паз (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Четверть (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Наклонный пил (м.п.)</th>
            <th  style=" text-align: center;padding:3px;">Криволинейный пил (шт.)</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">2</td>
            <td style=" text-align: left;padding:3px;">1</td>
            <td style=" text-align: left;padding:3px;">1</td>
        </tr>
    </tbody>
</table>

<br>
<br>
<table style="width:100%; border: 0; border-collapse: collapse; text-align: left;" border="1" >
    <tr >
        <td colspan="3" style=" text-align: left; font-size: 20px; padding-left: 10px;">Присадка (общее количество)</td>
    </tr>
    <thead>
        <tr>
            <th  style=" text-align: center; padding:3px;">1 - 10 мм</th>
            <th  style=" text-align: center; padding:3px;">11 - 20 мм</th>
            <th  style=" text-align: center; padding:3px;">21 - 35 мм</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style=" text-align: left; padding:3px;">1</td>
            <td style=" text-align: left; padding:3px;">0</td>
            <td style=" text-align: left; padding:3px;">1</td>
        </tr>
    </tbody>
</table>