controllers/OrdersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Orders;
use app\models\search\OrdersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Temporaries;
use app\models\OrdersAdditional;
use app\models\Ldsp;
use app\models\OrdersLdsp;
use yii\data\ActiveDataProvider;
use kartik\mpdf\Pdf;
use yii\web\UploadedFile;
use yii\base\ErrorException;
use app\models\Users;

class OrdersController extends Controller
{
   
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionView($id)
    {   
        $model = $this->findModel($id);
        $request = Yii::$app->request;
        $additionals = OrdersAdditional::find()->where(['order_id' => $id])->all();

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['order_id' => $id, 'ldsp.type' => 'ЛДСП']);
        $OrderLdsp = new ActiveDataProvider([
            'query' => $query,
        ]);

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['order_id' => $id, 'ldsp.type' => 'Оргалит']);
        $OrderOrgalit = new ActiveDataProvider([
            'query' => $query,
        ]);

        

        return $this->render('view', [
            'model' => $this->findModel($id),
            'additionals' => $additionals,
            'OrderLdsp' => $OrderLdsp,
            'OrderOrgalit' => $OrderOrgalit,
        ]);
    }

    public function actionIndex()
    {    
        $searchModel = new OrdersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreateOrder($temporary_id)
    {
        $request = Yii::$app->request;
        $model = new Orders();
        $user = Yii::$app->user->identity;
        if($user != null) $model->type = 1;
        else $model->type = 2;

        if($request->isAjax){

            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()) {

                $temporary = Temporaries::findOne($temporary_id);
                $additionals = OrdersAdditional::find()->where(['temporary_id' => $temporary->id])->all();
                $OrderLdsp = OrdersLdsp::find()->joinWith(['ldsp'])->where(['temporary_id' => $temporary->id,])->all();
                foreach ($OrderLdsp as $value) {
                    $value->order_id = $model->id;
                    $value->temporary_id = null;
                    $value->save();
                }

                foreach ($additionals as $value) {
                    $value->order_id = $model->id;
                    $value->temporary_id = null;
                    $value->save();
                }

                $model->price = $temporary->price;
                $model->save();
                $model->resume = UploadedFile::getInstance($model, 'resume');
                $model->uploadResume();
                // ***************** PDF GENEREATE  SEND TO GAMIL ************************
                $price = 0; $file_name = "";
                
                $price = $model->price;
                $additionals = OrdersAdditional::find()->where(['order_id' => $model->id])->all();

                $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['order_id' => $model->id, 'ldsp.type' => 'ЛДСП']);
                $OrderLdsp = new ActiveDataProvider([
                    'query' => $query,
                ]);

                $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['order_id' => $model->id, 'ldsp.type' => 'Оргалит']);
                $OrderOrgalit = new ActiveDataProvider([
                    'query' => $query,
                ]);

                $file_name = $model->email;

                Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
                $headers = Yii::$app->response->headers;
                $headers->add('Content-Type', 'application/pdf');

                $content = $this->renderPartial('orders-ldsp/print-html',[
                    'model' => $model,
                    'price' => $price,
                    'additionals' => $additionals,
                    'OrderLdsp' => $OrderLdsp,
                    'OrderOrgalit' => $OrderOrgalit,
                ]);
                // setup kartik\mpdf\Pdf component
                $pdf = new Pdf([
                    'filename' => $file_name.'.pdf',
                    // set to use core fonts only
                    'mode' => Pdf::MODE_UTF8, 
                    // A4 paper format
                    'format' => Pdf::FORMAT_A4, 
                    // portrait orientation
                    'orientation' => Pdf::ORIENT_PORTRAIT, 
                    // stream to browser inline
                    'destination' => Pdf::DEST_BROWSER, 
                    // your html content input
                    'content' => $content,  
                    // format content from your own css file if needed or use the
                    // enhanced bootstrap css built by Krajee for mPDF formatting 
                    'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
                    // any css to be embedded if required
                    'cssInline' => '.kv-heading-1{font-size:18px}', 
                     // set mPDF properties on the fly
                    'options' => ['title' => 'Krajee Report Title'],
                     // call mPDF methods on the fly
                    'methods' => [ 
                        'SetHeader'=>['ПЕЧАТЬ РАСЧЕТА'], 
                        'SetFooter'=>['{PAGENO}'],
                    ]
                ]);
                // ****************************** END PDF GENERATE *************************
                $fileName = "";
                $fileName = $pdf->filename;
                $filePath = Yii::getAlias('@app/web/uploads/pdf/' . $fileName);

                $attachment =  $pdf->output($content, $filePath, Pdf::DEST_FILE);

                $model->sendSmsToEmail($filePath);
                return $this->redirect(['view', 'id' => $model->id]);
            }else{           
                return [
                    'title'=> "Отправить заявку",
                    'content'=>$this->renderAjax('_form', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Заказать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{

            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('_form', [
                    'model' => $model,
                ]);
            }
        }
       
    }
    
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Temporaries();
        $model->save();
        return $this->redirect(['/orders/temporary', 'id' => $model->id]);
    }

    public function actionTemporary($id)
    {   
        $request = Yii::$app->request;
        $model = Temporaries::findOne($id);
        $additionals = OrdersAdditional::find()->where(['temporary_id' => $model->id])->all();

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['temporary_id' => $model->id, 'ldsp.type' => 'ЛДСП']);
        $OrderLdsp = new ActiveDataProvider([
            'query' => $query,
        ]);

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['temporary_id' => $model->id, 'ldsp.type' => 'Оргалит']);
        $OrderOrgalit = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('create', [
            'model' => $model,
            'additionals' => $additionals,
            'OrderLdsp' => $OrderLdsp,
            'OrderOrgalit' => $OrderOrgalit,
        ]);
    }

    public function actionPrintTemporary($temporary_id)
    {
        $request = Yii::$app->request;
        $model = Temporaries::findOne($temporary_id);
        $additionals = OrdersAdditional::find()->where(['temporary_id' => $model->id])->all();

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['temporary_id' => $model->id, 'ldsp.type' => 'ЛДСП']);
        $OrderLdsp = new ActiveDataProvider([
            'query' => $query,
        ]);

        $query = OrdersLdsp::find()->joinWith(['ldsp'])->where(['temporary_id' => $model->id, 'ldsp.type' => 'Оргалит']);
        $OrderOrgalit = new ActiveDataProvider([
            'query' => $query,
        ]);

        Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'title'=> "Печать",
            'size' => 'large',
            'content'=>$this->renderAjax('print', [
                'model' => $model,
                'additionals' => $additionals,
                'OrderLdsp' => $OrderLdsp,
                'OrderOrgalit' => $OrderOrgalit,
            ]),
        ];       
    }

    public function actionPrint($id, $type = 2) {
        $price = 0; $file_name = "";
        if($type == 2) {
            $model = Temporaries::findOne($id);

controllers/OrdersLdspController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrdersLdsp;
use app\models\search\OrdersLdspSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Ldsp;
use app\models\Temporaries;

class OrdersLdspController extends Controller
{   
    public function actionSetLdsp( )
    {
        if(isset($_POST['ldsp']) && $_POST['ldsp'] != null) {
            $model = new OrdersLdsp();
            $model->ldsp_id = $_POST['ldsp'];
            $model->temporary_id = $_POST['temporary_id'];
            $model->save();
        }
    }

    public function actionLdspName($id = null)
    {  
        $datas = Ldsp::findOne($id);
        if($datas != null) {
            $ldsp_name = Ldsp::find()->where(['thickness' => $datas->thickness])->orderBy(['sorting'=>SORT_DESC])->all();
            foreach ($ldsp_name as $value) { 
                echo "<option value = '".$value->id."'>".$value->name."</option>" ;            
            }            
        }
    }

    public function actionSetValues($id , $attribute , $value)
    {
        $model = OrdersLdsp::findOne($id);
        if($attribute == 'width') { 
            if($value >=30 && $value <= 2780 ) $model->width = $value;  
            if($value > 2780) $model->width = 2780;
            if($value < 30) $model->width = 30;

        }

        if($attribute == 'height') { 
            if($value >=30 && $value <= 2050 ) $model->height = $value;  
            if($value > 2050) $model->height = 2050;
            if($value < 30) $model->height = 30;
        }

        if($attribute == 'count') {
            if($value >= 0 )$model->count = $value; else $model->count = 0;
        }
        if($attribute == 'edge_width_left_id') $model->edge_width_left_id = (integer)$value;
        if($attribute == 'edge_width_right_id') $model->edge_width_right_id = (integer)$value;
        if($attribute == 'edge_height_left_id') $model->edge_height_left_id = (integer)$value;
        if($attribute == 'edge_height_right_id') $model->edge_height_right_id = (integer)$value;
        if($attribute == 'comment') $model->comment = $value;
        
        $model->save();
        $price = $model->temporary->setPrice();

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $price . ' руб';
    }

     public function actionSendFile()
    {   
        $uname = $_POST['uname'];
        $model = OrdersLdsp::findOne($uname);

        if($_FILES['file'])
        {   
            if(file_exists('uploads/orders_ldsp/'.$model->file) && $model->file != null)
            {
                unlink('uploads/orders_ldsp/'.$model->file);
            }

            $uploadDir = \Yii::getAlias('@app').'/web/uploads/orders_ldsp/';
            $ext = "";
            $ext = substr(strrchr($_FILES['file']['name'], "."), 1); 

            $fPath =$model->id."-".Yii::$app->security->generateRandomString().$_FILES['file']['name'];
            if($ext != ""){
                $result = move_uploaded_file($_FILES['file']['tmp_name'], $uploadDir . $fPath);
                $model->file = $fPath;
                $model->save();
            }
            //return $this->redirect(['/orders/temporary', 'id' => $model->temporary_id]);
        }
    }

    public function actionDownloadFile($file)
    {   
        return Yii::$app->response->sendFile(Yii::getAlias('uploads/orders_ldsp/'.$file));
    }

    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $model = OrdersLdsp::findOne($id);
        if($model != null){
            if(file_exists('uploads/orders_ldsp/'.$model->file )&&$model->file != null)
            {
                unlink('uploads/orders_ldsp/'.$model->file );
            }
        }
        $model->delete();
        $temporary = Temporaries::findOne($model->temporary_id);
        $price = $temporary->setPrice();

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $price . ' руб';
    }

    protected function findModel($id)
    {
        if (($model = OrdersLdsp::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/orders/_columns.php
<?php
use yii\helpers\Url;

return [
    /*[
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],*/
    // [
    //     'class' => 'kartik\grid\SerialColumn',
    //     'width' => '30px',
    // ],
        [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
        'width' => '15px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date_cr',
        'content' => function($data) {
            if($data->date_cr != null) return date('H:i d.m.Y', strtotime($data->date_cr) );
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'user_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'price',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'file',
        'content' => function($data) {
            return $data->downloadFile();
        }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'template' => '{view} {delete}',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['data-pjax'=>'0','title'=>'Просмотр','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'], 
    ],

];   

views/orders/create.php
<?php

use yii\helpers\Html;
use kartik\touchspin\TouchSpin;
use app\models\Ldsp;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use johnitvn\ajaxcrud\CrudAsset;
use yii\bootstrap\Modal;

$this->title = 'Калькулятор';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse">
	<div class="panel-heading">
		<h4 class="panel-title">Выбор ЛДСП</h4>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-2">
				<label>Толщина</label>
				<?= kartik\select2\Select2::widget([
	                'name' => 'tolshina'.$model->id,
	                'id' => 'tolshina'.$model->id,
	                'data' => Ldsp::getThickness(),
	                'options' => [
	                    'placeholder' => 'Выберите',
	                    'onchange'=>'
                            $.post( "/orders-ldsp/ldsp-name?id='.'"+$(this).val(), function( data ){
                                $( "select#ldsp_name" ).html( data);
                            });' 
                        ], 
	                'size' => kartik\select2\Select2::SMALL,
	                'pluginOptions' => [ 
	                	'allowClear' => true
	                ],
            	]) ?>
			</div>
			<div class="col-md-4">
				<label>Цвет</label>
				<?= kartik\select2\Select2::widget([
	                'name' => 'ldsp'.$model->id,
	                'id' => 'ldsp_name',
	                'options' => [
	                    'placeholder' => 'Выберите',
	                ],
	                'size' => kartik\select2\Select2::SMALL,
	                'pluginOptions' => [ 
	                	'allowClear' => true
	                ],
	            ]) ?>
			</div>
			<div class="col-md-2">
				<label style="color:white;">.</label><br>
				<?= Html::button('Добавить деталь <i class="fa fa-plus"></i>',['title'=> 'Добавить деталь','class'=>'btn btn-warning','id'=>'create_ldsp']) ?>
			</div>
		</div>
		<br>
		<?php Pjax::begin(['enablePushState' => false, 'id' => 'crud-datatable']) ?>
		<div class="row">
			<div class="col-md-12 ">
					<?=GridView::widget([
		                'id'=>'crud-datatable',
		                'dataProvider' => $OrderLdsp,
		                //'filterModel' => $searchHistory,
		                'pjax'=>true,
		                'columns' => require(__DIR__.'/orders-ldsp/_columns.php'),
		                'striped' => true,
		                'summary' => false,
		                'condensed' => true,
		                'responsive' => true,
		            ])?>
			</div>
		</div>
		<?php Pjax::end() ?> 
	</div>
</div>

<div class="panel panel-inverse">
	<div class="panel-heading">
		<h4 class="panel-title">Оргалит</h4>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<label>Цвет</label>
				<?= Select2::widget([
	                'name' => 'orgalit' . $model->id,
	                'id' => 'orgalit_name' . $model->id,
	                'data' => Ldsp::getOrgalit(),
	                'options' => [
	                    'placeholder' => 'Выберите',
	                ],
	                'size' => Select2::SMALL,
	                'pluginOptions' => [ 
	                	'allowClear' => true
	                ],
	            ]) ?>
			</div>
			<div class="col-md-2">
				<label style="color:white;">.</label><br>
				<?= Html::button('Добавить деталь <i class="fa fa-plus"></i>',['title'=> 'Добавить деталь','class'=>'btn btn-warning','id'=>'orgalit_ldsp'.$model->id]) ?>
			</div>
		</div>
		<br>
		<?php Pjax::begin(['enablePushState' => false, 'id' => 'orgalit']) ?>
		<div class="row">
			<div class="col-md-12 ">
					<?=GridView::widget([
		                'id'=>'orgalit',
		                'dataProvider' => $OrderOrgalit,
		                //'filterModel' => $searchHistory,
		                'pjax'=>true,
		                'columns' => require(__DIR__.'/orders-ldsp/_columns_orgalit.php'),
		                'striped' => true,
		                'summary' => false,
		                'condensed' => true,
		                'responsive' => true,
		            ])?>
			</div>
		</div>
		<?php Pjax::end() ?> 
	</div>
</div>

<div class="panel panel-inverse">
	<div class="panel-heading">
		<h4 class="panel-title">Эскизы (общее количество)</h4>
	</div>
	<div class="panel-body bg-silver">
		<div class="row">	
			<?php foreach ($additionals as $value) { 
				if($value->additional->type_additional == 'Эскизы') {
			?>
				<div class="col-md-2">
					<?php 
						echo '<label class="control-label">' . $value->additional->name . '</label>';
						echo TouchSpin::widget([
						    'name' => 'ekskiz'.$value->id,
						    'value' => $value->count,
						    'id' => 'ekskiz'.$value->id,
						    'pluginOptions' => [
						        'buttonup_class' => 'btn btn-info', 
						        'buttondown_class' => 'btn btn-info', 
						        'buttonup_txt' => '<i class="glyphicon glyphicon-plus-sign"></i>', 
						        'buttondown_txt' => '<i class="glyphicon glyphicon-minus-sign"></i>',
						        
						    ],
						    'options'=>[
						    	'onchange'=>'
						    	var a = $( "#ekskiz'.$value->id.'" ).val();
                                $.post( "/orders/set-values?temporary_id='.$model->id.'&additional_id='.$value->id.'&value="+a, function( data ){ document.getElementById("total_price").innerText = data; });
						    		' 
						    ],
						]);
					?>
				</div>
			<?php } } ?>
		</div>
	</div>
</div>

<div class="panel panel-inverse">
	<div class="panel-heading">
		<h4 class="panel-title">Фрезеровка (общее количество)</h4>
	</div>
	<div class="panel-body bg-silver">
		<div class="row">	
			<?php foreach ($additionals as $value) { 
				if($value->additional->type_additional == 'Фрезеровка') {
			?>
				<div class="col-md-2">
					<?php 
						echo '<label class="control-label">' . $value->additional->name . '</label>';
						echo TouchSpin::widget([
						    'name' => 'frezerovka'.$value->id,
						    'value' => $value->count,
						    'id' => 'frezerovka'.$value->id,
						    'pluginOptions' => [
						        'buttonup_class' => 'btn btn-info', 
						        'buttondown_class' => 'btn btn-info', 
						        'buttonup_txt' => '<i class="glyphicon glyphicon-plus-sign"></i>', 
						        'buttondown_txt' => '<i class="glyphicon glyphicon-minus-sign"></i>'
						    ],
						    'options'=>[
							    'onchange'=>'
							    var a = $( "#frezerovka'.$value->id.'" ).val();
	                            $.post( "/orders/set-values?temporary_id='.$model->id.'&additional_id='.$value->id.'&value="+a, function( data ){ document.getElementById("total_price").innerText = data; });
							    	'
						    ],
						]);
					?>
				</div>
			<?php } } ?>
		</div>
	</div>
</div>

<div class="panel panel-inverse">
	<div class="panel-heading">
		<h4 class="panel-title">Присадка (общее количество)</h4>
	</div>
	<div class="panel-body bg-silver">
		<div class="row">	
			<?php foreach ($additionals as $value) { 
				if($value->additional->type_additional == 'Присадка') {
			?>
				<div class="col-md-2">
					<?php 
						echo '<label class="control-label">' . $value->additional->name . '</label>';
						echo TouchSpin::widget([
						    'name' => 'prisadka'.$value->id,
						    'value' => $value->count,
						    'id' => 'prisadka'.$value->id,
						    'pluginOptions' => [
						        'buttonup_class' => 'btn btn-info', 
						        'buttondown_class' => 'btn btn-info', 
						        'buttonup_txt' => '<i class="glyphicon glyphicon-plus-sign"></i>', 
						        'buttondown_txt' => '<i class="glyphicon glyphicon-minus-sign"></i>'
						    ],
						    'options'=>[
							    'onchange'=>'
							    	var a = $( "#prisadka'.$value->id.'" ).val();
	                                $.post( "/orders/set-values?temporary_id='.$model->id.'&additional_id='.$value->id.'&value="+a, function( data ){
	                                	document.getElementById("total_price").innerText = data; });
							    	'
						    ],
						]);
					?>
				</div>
			<?php } } ?>
		</div>
	</div>
</div>

<div class="panel panel-inverse">
	<div class="panel-body bg-warning">
		<span style="font-weight: bold; font-size: 18px;">Итоговая стоимость:</span> 
		<span style="margin-right: 20px; font-size: 18px; color:red;" id="total_price"><?=$model->price?> руб.</span>
		<?= Html::a('Отправить заявку <i class="fa fa-send"></i>', ['create-order', 'temporary_id' => $model->id], ['role'=>'modal-remote','title'=> 'Создать','class'=>'btn btn-warning']) ?>
		<?= Html::a('Распечетать <i class="fa fa-print"></i>', ['print-temporary', 'temporary_id' => $model->id], ['role'=>'modal-remote', 'title'=> 'Распечетать', 'class'=>'btn btn-warning']) ?>
	</div>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>
<script type="text/javascript" charset="utf-8" async defer>
	
		function uploadFileOrders(id){
			// alert(id);
		    var data = new FormData() ; 
		    var size = $( '#inputFile_submit'+id )[0].files[0].size;
		    if(size > 200 * 1024 * 1024){
		    	alert("файл слишком большой, максимальная(200 Mb)")
		    }else{
		    	data.append('file', $( '#inputFile_submit'+id )[0].files[0]) ; 
			    data.append('uname', $( '#uname'+id ).val()) ; 
			    $.ajax({
			    url: '/orders-ldsp/send-file',
			    type: 'POST',
			    data: data,
			    processData: false,
			    contentType: false,
			        success: function(data){ 
			        	 $.pjax.reload({container:'#crud-datatable', async: false});
			        	 $.pjax.reload({container:'#orgalit', async: false});
			       }
			    });
			    $.pjax.reload({container:'#crud-datatable', async: false});
			    $.pjax.reload({container:'#orgalit', async: false});
			    return false;
		    }
		    
		}
</script>

<script type="text/javascript" charset="utf-8" async defer>
	$(document).on('click', '#create_ldsp', function(e){
	        var ldsp = $( "#ldsp_name" ).val();
	        $.ajax({
	           type: 'POST',
	           data: {temporary_id: <?=$model->id?>, ldsp: ldsp },
	           url: '/orders-ldsp/set-ldsp',
	           success: function(data){ 
		        	$.pjax.reload({container:'#crud-datatable', async: false});
		        	$.pjax.reload({container:'#orgalit', async: false});
		       }
	        });
	        $.pjax.reload({container:'#crud-datatable', async: false});

	    });

</script>
<script type="text/javascript" charset="utf-8" async defer>
	$(document).on('click', '#orgalit_ldsp<?=$model->id?>', function(e){
	    var orgalit = $( "#orgalit_name<?=$model->id?>" ).val();
	    $.ajax({
	       type: 'POST',
	       data: {temporary_id: <?=$model->id?>, ldsp: orgalit },
	       url: '/orders-ldsp/set-ldsp',
	        success: function(data){ 
		        	$.pjax.reload({container:'#crud-datatable', async: false});
		        	$.pjax.reload({container:'#orgalit', async: false});
		       }
	    });
	    $.pjax.reload({container:'#orgalit', async: false});
	});

</script>

views/orders/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
?>
<div class="orders-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>